import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


/**
 * 
 * export async function getServerSideProps(context) {
  return {
    redirect: {
      destination: 'https://google.com',
      permanent: false
    },
    notFound: true
  }
}
 */

export async function getStaticProps(context) {
  console.log(context)

  return {
    props: {
      count: Math.floor(Math.random() * 10)
    }
  }
}

export default function Home(props) {

  console.log('My env: ', process.env.SECRET_KEY)
  console.log('Public key: ', process.env.NEXT_PUBLIC_SECRET)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {props.count} <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}
