import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export async function getServerSideProps(context) {
  return {
    redirect: {
      destination: 'https://google.com',
      permanent: false
    }
  }
}

export default function Home() {

  console.log('My env: ', process.env.SECRET_KEY)
  console.log('Public key: ', process.env.NEXT_PUBLIC_SECRET)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}
